09/24/25 03:26:25 AM : INFO : Testing Directory: /app
09/24/25 03:26:25 AM : Test Start : Running Tests for: ECE461: Autograder Phase 1 CLI Checker
09/24/25 03:26:25 AM : Test Start : Running Tests for: Basic Sanity
09/24/25 03:26:25 AM : DEBUG : Running test: Basic Sanity
09/24/25 03:26:25 AM : DEBUG : Running test: Install Test
09/24/25 03:26:35 AM : Test Debug : Output Valid: True
09/24/25 03:26:35 AM : Test Success : > Install command ran and exited successfully!
09/24/25 03:26:35 AM : Run Stdout : Requirement already satisfied: requests>=2.25.0 in /usr/local/lib/python3.9/dist-packages (from -r /app/data/111/repo/requirements.txt (line 2)) (2.32.3)
Collecting beautifulsoup4>=4.9.0
  Downloading beautifulsoup4-4.13.5-py3-none-any.whl (105 kB)
Collecting lxml>=4.6.0
  Downloading lxml-6.0.2-cp39-cp39-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.3 MB)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.9/dist-packages (from -r /app/data/111/repo/requirements.txt (line 5)) (2.9.0.post0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.9/dist-packages (from -r /app/data/111/repo/requirements.txt (line 6)) (1.26.20)
Requirement already satisfied: GitPython>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from -r /app/data/111/repo/requirements.txt (line 7)) (3.1.43)
Collecting PyGithub>=1.55.0
  Downloading pygithub-2.8.1-py3-none-any.whl (432 kB)
Collecting huggingface-hub>=0.10.0
  Downloading huggingface_hub-0.35.1-py3-none-any.whl (563 kB)
Collecting flake8==7.0.0
  Downloading flake8-7.0.0-py2.py3-none-any.whl (57 kB)
Collecting black==25.9.0
  Downloading black-25.9.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (1.6 MB)
Collecting pre-commit==4.3.0
  Downloading pre_commit-4.3.0-py2.py3-none-any.whl (220 kB)
Collecting pytest==8.3.2
  Downloading pytest-8.3.2-py3-none-any.whl (341 kB)
Requirement already satisfied: typing-extensions>=4.0.1 in /usr/local/lib/python3.9/dist-packages (from black==25.9.0->-r /app/data/111/repo/requirements.txt (line 13)) (4.15.0)
Collecting platformdirs>=2
  Downloading platformdirs-4.4.0-py3-none-any.whl (18 kB)
Collecting tomli>=1.1.0
  Downloading tomli-2.2.1-py3-none-any.whl (14 kB)
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.9/dist-packages (from black==25.9.0->-r /app/data/111/repo/requirements.txt (line 13)) (8.1.8)
Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.9/dist-packages (from black==25.9.0->-r /app/data/111/repo/requirements.txt (line 13)) (25.0)
Collecting pytokens>=0.1.10
  Downloading pytokens-0.1.10-py3-none-any.whl (12 kB)
Collecting pathspec>=0.9.0
  Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
Collecting pycodestyle<2.12.0,>=2.11.0
  Downloading pycodestyle-2.11.1-py2.py3-none-any.whl (31 kB)
Collecting pyflakes<3.3.0,>=3.2.0
  Downloading pyflakes-3.2.0-py2.py3-none-any.whl (62 kB)
Collecting mccabe<0.8.0,>=0.7.0
  Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting virtualenv>=20.10.0
  Downloading virtualenv-20.34.0-py3-none-any.whl (6.0 MB)
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.9.1-py2.py3-none-any.whl (22 kB)
Collecting cfgv>=2.0.0
  Downloading cfgv-3.4.0-py2.py3-none-any.whl (7.2 kB)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (737 kB)
Collecting identify>=1.0.0
  Downloading identify-2.6.14-py2.py3-none-any.whl (99 kB)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.9/dist-packages (from pytest==8.3.2->-r /app/data/111/repo/requirements.txt (line 15)) (1.3.0)
Collecting iniconfig
  Downloading iniconfig-2.1.0-py3-none-any.whl (6.0 kB)
Collecting pluggy<2,>=1.5
  Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.8-py3-none-any.whl (36 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.9/dist-packages (from GitPython>=3.1.0->-r /app/data/111/repo/requirements.txt (line 7)) (4.0.12)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub>=0.10.0->-r /app/data/111/repo/requirements.txt (line 9)) (4.66.5)
Collecting fsspec>=2023.5.0
  Downloading fsspec-2025.9.0-py3-none-any.whl (199 kB)
Collecting hf-xet<2.0.0,>=1.1.3
  Downloading hf_xet-1.1.10-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
Collecting filelock
  Downloading filelock-3.19.1-py3-none-any.whl (15 kB)
Collecting pyjwt[crypto]>=2.4.0
  Downloading PyJWT-2.10.1-py3-none-any.whl (22 kB)
Collecting pynacl>=1.4.0
  Downloading pynacl-1.6.0-cp38-abi3-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.0->-r /app/data/111/repo/requirements.txt (line 5)) (1.17.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.25.0->-r /app/data/111/repo/requirements.txt (line 2)) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.25.0->-r /app/data/111/repo/requirements.txt (line 2)) (2025.8.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.25.0->-r /app/data/111/repo/requirements.txt (line 2)) (3.4.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.9/dist-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.0->-r /app/data/111/repo/requirements.txt (line 7)) (5.0.2)
Collecting cryptography>=3.4.0
  Downloading cryptography-46.0.1-cp38-abi3-manylinux_2_28_x86_64.whl (4.6 MB)
Collecting cffi>=2.0.0
  Downloading cffi-2.0.0-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216 kB)
Collecting pycparser
  Downloading pycparser-2.23-py3-none-any.whl (118 kB)
Collecting distlib<1,>=0.3.7
  Downloading distlib-0.4.0-py2.py3-none-any.whl (469 kB)
Installing collected packages: pycparser, cffi, pyjwt, platformdirs, filelock, distlib, cryptography, virtualenv, tomli, soupsieve, pyyaml, pytokens, pynacl, pyflakes, pycodestyle, pluggy, pathspec, nodeenv, mypy-extensions, mccabe, iniconfig, identify, hf-xet, fsspec, cfgv, pytest, PyGithub, pre-commit, lxml, huggingface-hub, flake8, black, beautifulsoup4
Successfully installed PyGithub-2.8.1 beautifulsoup4-4.13.5 black-25.9.0 cffi-2.0.0 cfgv-3.4.0 cryptography-46.0.1 distlib-0.4.0 filelock-3.19.1 flake8-7.0.0 fsspec-2025.9.0 hf-xet-1.1.10 huggingface-hub-0.35.1 identify-2.6.14 iniconfig-2.1.0 lxml-6.0.2 mccabe-0.7.0 mypy-extensions-1.1.0 nodeenv-1.9.1 pathspec-0.12.1 platformdirs-4.4.0 pluggy-1.6.0 pre-commit-4.3.0 pycodestyle-2.11.1 pycparser-2.23 pyflakes-3.2.0 pyjwt-2.10.1 pynacl-1.6.0 pytest-8.3.2 pytokens-0.1.10 pyyaml-6.0.2 soupsieve-2.8 tomli-2.2.1 virtualenv-20.34.0
Dependencies installed successfully

09/24/25 03:26:35 AM : Run Stderr : 
09/24/25 03:26:35 AM : DEBUG : Running test: Test Suite Test
09/24/25 03:26:35 AM : Test Debug : Output Valid: True
09/24/25 03:26:35 AM : Test Success : > Test Suite command ran and exited successfully!
09/24/25 03:26:35 AM : Run Stdout : ============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-8.3.2, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /app/data/111/repo
configfile: pyproject.toml
plugins: anyio-4.10.0
collecting ... collected 8 items

tests/test_data_quality.py::TestDatasetQualityMetric::test_example_count_extraction PASSED [ 12%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_initialization PASSED [ 25%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_metadata_completeness PASSED [ 37%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_non_dataset_returns_zero PASSED [ 50%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_get_description PASSED [ 62%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_initialization PASSED [ 75%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_ml_integration_detection PASSED [ 87%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_score_calculation PASSED [100%]

============================== 8 passed in 0.01s ===============================

09/24/25 03:26:35 AM : Run Stderr : 
09/24/25 03:26:35 AM : DEBUG : Running test: URL File Test
09/24/25 03:26:35 AM : Run Stderr : Output does not match the number of urls in the file
09/24/25 03:26:35 AM : Test Debug : Output Valid: False
09/24/25 03:26:35 AM : Test Fail : > URL File command did not exit successfully!
09/24/25 03:26:35 AM : Run Stdout : None
09/24/25 03:26:35 AM : Run Stderr : Traceback (most recent call last):
  File "/app/data/111/repo/run.py", line 97, in <module>
    run_cli()
  File "/app/data/111/repo/src/cli.py", line 79, in run_cli
    process_and_score_input_file(input_file)
  File "/app/data/111/repo/src/cli.py", line 25, in process_and_score_input_file
    metadata: Dict[str, Any] = fetch_metadata(entry)
  File "/app/data/111/repo/src/utils/parse_input.py", line 63, in fetch_metadata
    category = entry["category"]
KeyError: 'category'

09/24/25 03:26:35 AM : Test Result : Total score: 2 / 3 

09/24/25 03:26:35 AM : Test Start : Running Tests for: Test Suite Basic Sanity
09/24/25 03:26:35 AM : DEBUG : Running test: Test Suite Basic Sanity
09/24/25 03:26:35 AM : DEBUG : Running test: Test Suite Test
09/24/25 03:26:35 AM : Test Debug : Output Valid: True
09/24/25 03:26:35 AM : Test Success : > Test Suite command ran and exited successfully!
09/24/25 03:26:35 AM : Run Stdout : ============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-8.3.2, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /app/data/111/repo
configfile: pyproject.toml
plugins: anyio-4.10.0
collecting ... collected 8 items

tests/test_data_quality.py::TestDatasetQualityMetric::test_example_count_extraction PASSED [ 12%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_initialization PASSED [ 25%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_metadata_completeness PASSED [ 37%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_non_dataset_returns_zero PASSED [ 50%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_get_description PASSED [ 62%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_initialization PASSED [ 75%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_ml_integration_detection PASSED [ 87%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_score_calculation PASSED [100%]

============================== 8 passed in 0.01s ===============================

09/24/25 03:26:35 AM : Run Stderr : None
09/24/25 03:26:35 AM : DEBUG : Running test: Test Suite - Check output syntax
09/24/25 03:26:35 AM : Test Debug : Output Valid: None
09/24/25 03:26:35 AM : Test Fail : > Output syntax is incorrect.
09/24/25 03:26:35 AM : Run Stdout : ============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-8.3.2, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /app/data/111/repo
configfile: pyproject.toml
plugins: anyio-4.10.0
collecting ... collected 8 items

tests/test_data_quality.py::TestDatasetQualityMetric::test_example_count_extraction PASSED [ 12%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_initialization PASSED [ 25%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_metadata_completeness PASSED [ 37%]
tests/test_data_quality.py::TestDatasetQualityMetric::test_non_dataset_returns_zero PASSED [ 50%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_get_description PASSED [ 62%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_initialization PASSED [ 75%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_ml_integration_detection PASSED [ 87%]
tests/test_dataset_and_code_score.py::TestDatasetAndCodeMetric::test_score_calculation PASSED [100%]

============================== 8 passed in 0.01s ===============================

09/24/25 03:26:35 AM : Run Stderr : None
09/24/25 03:26:35 AM : Test Result : Total score: 1 / 2 

09/24/25 03:26:35 AM : Test Start : Running Tests for: URL File Basic Tests
09/24/25 03:26:35 AM : DEBUG : Running test: URL File Basic Tests
09/24/25 03:26:35 AM : DEBUG : Running test: URL File Test
09/24/25 03:26:35 AM : Run Stderr : Output does not match the number of urls in the file
09/24/25 03:26:35 AM : Test Debug : Output Valid: False
09/24/25 03:26:35 AM : Test Fail : > URL File command did not exit successfully!
09/24/25 03:26:35 AM : Run Stdout : 

09/24/25 03:26:35 AM : Run Stderr : Traceback (most recent call last):
  File "/app/data/111/repo/run.py", line 97, in <module>
    run_cli()
  File "/app/data/111/repo/src/cli.py", line 79, in run_cli
    process_and_score_input_file(input_file)
  File "/app/data/111/repo/src/cli.py", line 25, in process_and_score_input_file
    metadata: Dict[str, Any] = fetch_metadata(entry)
  File "/app/data/111/repo/src/utils/parse_input.py", line 63, in fetch_metadata
    category = entry["category"]
KeyError: 'category'

09/24/25 03:26:35 AM : DEBUG : Running test: Valid JSON Output Test
09/24/25 03:26:35 AM : Test Fail : > URL File is not valid NDJSON! (Unstaisfied dependency 'URL File Test')
09/24/25 03:26:35 AM : Run Stdout : None
09/24/25 03:26:35 AM : Run Stderr : None
09/24/25 03:26:35 AM : DEBUG : Running test: Valid Score Ranges Test
09/24/25 03:26:35 AM : Test Fail : > URL File does not have valid field ranges! (Unstaisfied dependency 'Valid JSON Output Test')
09/24/25 03:26:35 AM : Run Stdout : None
09/24/25 03:26:35 AM : Run Stderr : None
09/24/25 03:26:35 AM : DEBUG : Running test: Valid Net Score Test
09/24/25 03:26:35 AM : Test Fail : > URL File does not have valid NET_SCORE! (Unstaisfied dependency 'Valid Score Ranges Test')
09/24/25 03:26:35 AM : Run Stdout : None
09/24/25 03:26:35 AM : Run Stderr : None
09/24/25 03:26:35 AM : DEBUG : Running test: Valid Net Score Latency Test
09/24/25 03:26:35 AM : Test Fail : > URL File does not have valid NET_SCORE and LATENCY! (Unstaisfied dependency 'Valid Score Ranges Test')
09/24/25 03:26:35 AM : Run Stdout : None
09/24/25 03:26:35 AM : Run Stderr : None
09/24/25 03:26:35 AM : Test Result : Total score: 0 / 5 

09/24/25 03:26:35 AM : Test Start : Running Tests for: Environment Variable Basic Sanity
09/24/25 03:26:35 AM : DEBUG : Running test: Environment Variable Basic Sanity
09/24/25 03:26:35 AM : DEBUG : Running test: Invalid GitHub Token Test
09/24/25 03:26:36 AM : Test Debug : Output Valid: True
09/24/25 03:26:36 AM : Test Success : > Invalid GitHub Token Test passed!
09/24/25 03:26:36 AM : Run Stdout : Traceback (most recent call last):
  File "/app/data/111/repo/run.py", line 97, in <module>
    run_cli()
  File "/app/data/111/repo/src/cli.py", line 79, in run_cli
    process_and_score_input_file(input_file)
  File "/app/data/111/repo/src/cli.py", line 25, in process_and_score_input_file
    metadata: Dict[str, Any] = fetch_metadata(entry)
  File "/app/data/111/repo/src/utils/parse_input.py", line 63, in fetch_metadata
    category = entry["category"]
KeyError: 'category'

09/24/25 03:26:36 AM : Run Stderr : Traceback (most recent call last):
  File "/app/data/111/repo/run.py", line 97, in <module>
    run_cli()
  File "/app/data/111/repo/src/cli.py", line 79, in run_cli
    process_and_score_input_file(input_file)
  File "/app/data/111/repo/src/cli.py", line 25, in process_and_score_input_file
    metadata: Dict[str, Any] = fetch_metadata(entry)
  File "/app/data/111/repo/src/utils/parse_input.py", line 63, in fetch_metadata
    category = entry["category"]
KeyError: 'category'

09/24/25 03:26:36 AM : DEBUG : Running test: Invalid Log File Path Test
09/24/25 03:26:36 AM : Test Debug : Output Valid: True
09/24/25 03:26:36 AM : Test Success : > Invalid Log File Path Test passed!
09/24/25 03:26:36 AM : Run Stdout : Traceback (most recent call last):
  File "/app/data/111/repo/run.py", line 97, in <module>
    run_cli()
  File "/app/data/111/repo/src/cli.py", line 79, in run_cli
    process_and_score_input_file(input_file)
  File "/app/data/111/repo/src/cli.py", line 25, in process_and_score_input_file
    metadata: Dict[str, Any] = fetch_metadata(entry)
  File "/app/data/111/repo/src/utils/parse_input.py", line 63, in fetch_metadata
    category = entry["category"]
KeyError: 'category'

09/24/25 03:26:36 AM : Run Stderr : Traceback (most recent call last):
  File "/app/data/111/repo/run.py", line 97, in <module>
    run_cli()
  File "/app/data/111/repo/src/cli.py", line 79, in run_cli
    process_and_score_input_file(input_file)
  File "/app/data/111/repo/src/cli.py", line 25, in process_and_score_input_file
    metadata: Dict[str, Any] = fetch_metadata(entry)
  File "/app/data/111/repo/src/utils/parse_input.py", line 63, in fetch_metadata
    category = entry["category"]
KeyError: 'category'

09/24/25 03:26:36 AM : DEBUG : Running test: Log Level Test
09/24/25 03:26:36 AM : Test Debug : Output Valid: False
09/24/25 03:26:36 AM : Test Fail : > Blank file is not produced for Log Level 0 Test!
09/24/25 03:26:36 AM : Run Stdout : None
09/24/25 03:26:36 AM : Run Stderr : Traceback (most recent call last):
  File "/app/data/111/repo/run.py", line 97, in <module>
    run_cli()
  File "/app/data/111/repo/src/cli.py", line 79, in run_cli
    process_and_score_input_file(input_file)
  File "/app/data/111/repo/src/cli.py", line 25, in process_and_score_input_file
    metadata: Dict[str, Any] = fetch_metadata(entry)
  File "/app/data/111/repo/src/utils/parse_input.py", line 63, in fetch_metadata
    category = entry["category"]
KeyError: 'category'

09/24/25 03:26:36 AM : Test Result : Total score: 2 / 3 

09/24/25 03:26:36 AM : Test Result : Total score: 5 / 13 

